/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Warkarma (https://sketchfab.com/warkarma)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/winter-at-home-holiday2020challenge-6dd58b216b7e4b56b4c246b217845e66
title: Winter at home - Holiday2020Challenge
*/  

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function House(props) {
  const { nodes, materials } = useGLTF('/house.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[4.34, 7.54, 2.57]} rotation={[-0.24, 0.91, 1.8]} scale={0.08}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.Snow_Flakes} />
          </group>
          <group position={[-0.09, 3.2, -1.03]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['Snow.002']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['Snow.002']} />
            <mesh geometry={nodes.Object_8.geometry} material={materials['Snow.002']} />
          </group>
          <group position={[1.57, 0.7, -1.23]}>
            <mesh geometry={nodes.Object_10.geometry} material={materials.wood2} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Window} />
          </group>
          <group position={[0.05, 0.79, -1.47]} rotation={[-2.96, 0.64, -1.64]}>
            <mesh geometry={nodes.Object_13.geometry} material={materials.Snow_Flakes} />
          </group>
          <group position={[0, 1, 0.05]}>
            <mesh geometry={nodes.Object_15.geometry} material={materials.wood2} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.Wood} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.Window} />
          </group>
          <group position={[0, 2.33, -1]}>
            <mesh geometry={nodes.Object_19.geometry} material={materials.Metal} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.Wood} />
            <mesh geometry={nodes.Object_21.geometry} material={materials.wood2} />
          </group>
          <group position={[-0.06, 2.71, -1.05]}>
            <mesh geometry={nodes.Object_23.geometry} material={materials.wood2} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.Window} />
          </group>
          <group position={[-1.5, -0.05, -1.1]}>
            <mesh geometry={nodes.Object_26.geometry} material={materials.wood2} />
          </group>
          <group position={[0.08, 0.44, 1.91]}>
            <mesh geometry={nodes.Object_28.geometry} material={materials.wood2} />
            <mesh geometry={nodes.Object_29.geometry} material={materials.Wood} />
          </group>
          <group position={[0.89, 0.44, -3.5]}>
            <mesh geometry={nodes.Object_31.geometry} material={materials.wood2} />
            <mesh geometry={nodes.Object_32.geometry} material={materials.Wood} />
          </group>
          <group position={[2.89, 0.44, -1.89]}>
            <mesh geometry={nodes.Object_34.geometry} material={materials.wood2} />
            <mesh geometry={nodes.Object_35.geometry} material={materials.Wood} />
          </group>
          <group position={[2.5, -0.22, 0.91]}>
            <mesh geometry={nodes.Object_37.geometry} material={materials.wood2} />
            <mesh geometry={nodes.Object_38.geometry} material={materials.Wood} />
          </group>
          <group position={[-4.05, -0.48, -1.21]}>
            <mesh geometry={nodes.Object_40.geometry} material={materials.Rocks} />
          </group>
          <group position={[0, 1.79, -1.77]}>
            <mesh geometry={nodes.Object_42.geometry} material={materials.Snow} />
          </group>
          <group position={[-2.64, -0.57, 0.68]}>
            <mesh geometry={nodes.Object_44.geometry} material={materials['Tree_Trunk.001']} />
          </group>
          <group position={[-3.92, -0.57, -3.4]}>
            <mesh geometry={nodes.Object_46.geometry} material={materials['Tree_Trunk.001']} />
          </group>
          <group position={[3.55, -0.57, -7.32]}>
            <mesh geometry={nodes.Object_48.geometry} material={materials.Wood} />
          </group>
          <group position={[-3.29, -0.79, -4.16]}>
            <mesh geometry={nodes.Object_50.geometry} material={materials['Tree_Trunk.001']} />
            <mesh geometry={nodes.Object_51.geometry} material={materials.Pine_Tree} />
          </group>
          <group position={[4.49, -0.57, -3.42]}>
            <mesh geometry={nodes.Object_53.geometry} material={materials['Tree_Trunk.001']} />
            <mesh geometry={nodes.Object_54.geometry} material={materials.Pine_Tree} />
          </group>
          <group position={[-2.64, -0.96, 2.94]}>
            <mesh geometry={nodes.Object_56.geometry} material={materials['Tree_Trunk.001']} />
            <mesh geometry={nodes.Object_57.geometry} material={materials.Pine_Tree} />
          </group>
          <group position={[0.24, -1.32, -4.54]}>
            <mesh geometry={nodes.Object_59.geometry} material={materials['Tree_Trunk.001']} />
            <mesh geometry={nodes.Object_60.geometry} material={materials.Pine_Tree} />
          </group>
          <group position={[-4.68, -0.32, -3.41]}>
            <mesh geometry={nodes.Object_62.geometry} material={materials['Tree_Trunk.001']} />
            <mesh geometry={nodes.Object_63.geometry} material={materials.Pine_Tree} />
          </group>
          <group position={[5.42, -0.58, -2.73]}>
            <mesh geometry={nodes.Object_65.geometry} material={materials['Tree_Trunk.001']} />
            <mesh geometry={nodes.Object_66.geometry} material={materials.Pine_Tree} />
          </group>
          <group position={[-6.56, -0.65, -1.53]}>
            <mesh geometry={nodes.Object_68.geometry} material={materials.Pine_Tree} />
            <mesh geometry={nodes.Object_69.geometry} material={materials['Tree_Trunk.001']} />
          </group>
          <group position={[-6.06, -0.22, -2.55]}>
            <mesh geometry={nodes.Object_71.geometry} material={materials.Pine_Tree} />
            <mesh geometry={nodes.Object_72.geometry} material={materials['Tree_Trunk.001']} />
          </group>
          <group position={[1.74, -0.6, -8.5]}>
            <mesh geometry={nodes.Object_74.geometry} material={materials.Pine_Tree} />
            <mesh geometry={nodes.Object_75.geometry} material={materials['Tree_Trunk.001']} />
          </group>
          <group position={[-3.68, -1.02, 3.7]}>
            <mesh geometry={nodes.Object_77.geometry} material={materials.Pine_Tree} />
            <mesh geometry={nodes.Object_78.geometry} material={materials['Tree_Trunk.001']} />
          </group>
          <group position={[-2.58, -0.99, 5.17]}>
            <mesh geometry={nodes.Object_80.geometry} material={materials.Pine_Tree} />
            <mesh geometry={nodes.Object_81.geometry} material={materials['Tree_Trunk.001']} />
          </group>
          <group position={[4.55, -0.69, -2.27]}>
            <mesh geometry={nodes.Object_83.geometry} material={materials['Tree_Trunk.001']} />
            <mesh geometry={nodes.Object_84.geometry} material={materials.Pine_Tree} />
          </group>
          <group position={[-2.84, -0.61, 4.24]}>
            <mesh geometry={nodes.Object_86.geometry} material={materials.Wood} />
          </group>
          <group position={[5.65, -0.41, -6.81]}>
            <mesh geometry={nodes.Object_88.geometry} material={materials.Wood} />
          </group>
          <group position={[0.3, -0.23, -9.27]}>
            <mesh geometry={nodes.Object_90.geometry} material={materials.Wood} />
          </group>
          <group position={[0.61, -0.65, 2.35]}>
            <mesh geometry={nodes.Object_92.geometry} material={materials['Bush_Material.001']} />
          </group>
          <group position={[1.22, -0.67, 2.15]}>
            <mesh geometry={nodes.Object_94.geometry} material={materials['Bush_Material.001']} />
          </group>
          <group position={[-2.56, -0.7, 1.64]}>
            <mesh geometry={nodes.Object_96.geometry} material={materials['Bush_Material.001']} />
          </group>
          <group position={[1.07, -0.54, -4.43]}>
            <mesh geometry={nodes.Object_98.geometry} material={materials['Bush_Material.001']} />
          </group>
          <group position={[-3.01, -0.45, 1.15]}>
            <mesh geometry={nodes.Object_100.geometry} material={materials['Bush_Material.001']} />
          </group>
          <group position={[-2.98, -0.55, 2.06]}>
            <mesh geometry={nodes.Object_102.geometry} material={materials['Bush_Material.001']} />
          </group>
          <group position={[3.46, -0.42, -2.32]}>
            <mesh geometry={nodes.Object_104.geometry} material={materials['Bush_Material.001']} />
          </group>
          <group position={[3.31, -0.44, -2.94]}>
            <mesh geometry={nodes.Object_106.geometry} material={materials['Bush_Material.001']} />
          </group>
          <group position={[3.29, -0.48, 0.29]}>
            <mesh geometry={nodes.Object_108.geometry} material={materials['Bush_Material.001']} />
          </group>
          <group position={[5.57, -0.44, 0.31]}>
            <mesh geometry={nodes.Object_110.geometry} material={materials.Wood} />
            <mesh geometry={nodes.Object_111.geometry} material={materials['Snow.001']} />
            <mesh geometry={nodes.Object_112.geometry} material={materials.Black} />
            <mesh geometry={nodes.Object_113.geometry} material={materials.orange} />
          </group>
          <group position={[3.33, -0.69, 4.95]}>
            <mesh geometry={nodes.Object_115.geometry} material={materials['Tree_Trunk.001']} />
            <mesh geometry={nodes.Object_116.geometry} material={materials.Pine_Tree} />
          </group>
          <group position={[0.77, 2.84, -1.5]}>
            <mesh geometry={nodes.Object_118.geometry} material={materials.Chimney} />
          </group>
          <group position={[0.71, 5.66, -1.41]}>
            <mesh geometry={nodes.Object_120.geometry} material={materials.Smoke} />
          </group>
          <group position={[-0.09, 3.2, -1.03]}>
            <mesh geometry={nodes.Object_122.geometry} material={materials.Snow} />
            <mesh geometry={nodes.Object_123.geometry} material={materials.Snow} />
            <mesh geometry={nodes.Object_124.geometry} material={materials.Snow} />
            <mesh geometry={nodes.Object_125.geometry} material={materials.Snow} />
            <mesh geometry={nodes.Object_126.geometry} material={materials.Snow} />
            <mesh geometry={nodes.Object_127.geometry} material={materials.Snow} />
            <mesh geometry={nodes.Object_128.geometry} material={materials.Snow} />
            <mesh geometry={nodes.Object_129.geometry} material={materials.Snow} />
            <mesh geometry={nodes.Object_130.geometry} material={materials.Snow} />
            <mesh geometry={nodes.Object_131.geometry} material={materials.Snow} />
            <mesh geometry={nodes.Object_132.geometry} material={materials.Snow} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/house.gltf')
